### ISSUE TITLE
feat(slides): Component & Integration Testing Fallback

### ISSUE THREAD

**Issue by maartentibau** [rainerhahnekamp/eternal#5]
On slide `19` the `fireEvent` method is mentioned there. On the next slide the `userEvent` method is explained. But maybe it might be a good idea to add a link in slide `19` for reference.

In the docs of `Testing Library` they nicely explain why `userEvent` is more in favour of `fireEvent` in most cases. Dunno if it might be useful to add a link to that explanation.

URL: https://testing-library.com/docs/user-event/intro

**Comment by rainerhahnekamp** [comment]
Done
